#!/bin/bash

POLICY_PROG="$1";
shift

if [ -z "$1" ]; then
    echo "Usage: ./writelimiter policy_commandline argv...\n"
    exit 1
fi

export LIMIT_SYSCALLS_DEFAULT_ACTION=a

./writelimiter_broker \
    "$POLICY_PROG" \
    /usr/bin/env \
        LD_PRELOAD=`pwd`/libwritelimiter.so \
        ../limit_syscalls    \
            'open,A1&&0x03==0x01,e1' \
            'open,A1&&0x03==0x02,e1' \
            'open,A1&&0x40==0x40,e1' \
            rmdir,e1 \
            mkdir,e1 \
            -- "$@"
