#!/bin/bash

export LIMIT_SYSCALLS_DEFAULT_ACTION=a

./writelimiter_broker /usr/bin/env LD_PRELOAD=`pwd`/libwritelimiter.so ../limit_syscalls    'open,A1&&0x03==0x01,e1' 'open,A1&&0x03==0x02,e1' -- "$@"